### ISSUE TITLE
Replace JsonPath with JsonPointer

### ISSUE THREAD

**Issue by r0goyal** [santanusinha/hope#14]
Today hope uses JsonPath for evaluating value of dynamic `JsonPathValue`. 

Given that hope relies on very minimal functionality of `JsonPath` (Only direct path lookups), the same can be achieved by using Json Pointers (https://datatracker.ietf.org/doc/html/rfc6901) which is natively supported by Jackson. 

@santanusinha Have tried to take a crack at in https://github.com/santanusinha/hope/pull/13

**Open points**

- Implementation in MR is backward compatible with existing `JsonPath` based expressions and supports native Json Pointers as well. This is done by introspecting the path expression and distinguishing between `JsonPath` and `JsonPointer` by their corresponding prefixes. Does this suffice ?
- Do we want an option in HopeLangEngine which can force all path expressions to follow `Json Pointer` typed expressions ?

**Comment by santanusinha** [comment]
This will break in existing places where people have used path expressions anything beyond the very basic usage of pointers. With #15 ,  pointers are supported now in hope. Path support will be deprecated and removed in a future version.
